- name: play1 
  hosts: localhost
  become: no 
  tasks:
  - name: play1 task1
    ansible.builtin.debug:
      msg: "Play 1 Task 1"
  - name: play1 task2
    ansible.builtin.debug:
      msg: "Play 1 task 2"

- name: pay2
  hosts: localhost
  become: no 
  tasks:
  - name: play2 task1
    ansible.builtin.debug:
      msg: "Play2 task1"
  - name: play2 task2
    ansible.builtin.debug:
      msg: "Play2 task2"    