- name: var check
  hosts: localhost
  become: no 
  # vars:
  #   Course: Devops

  # vars_prompt:
  # - name: USERNAME
  #   prompt: "ENter username"
  #   private: no 


  # - name: PASSWORD
  #   prompt: "ENter password:"
  #   private: yes  

  - vars_files:
    var1.yaml  

  tasks:
  - name: var check inheritance
    # vars: 
    #   Course: Terraform
    ansible.builtin.debug:
      msg: "{{Course}}"

  - name: var check overrider  
    ansible.builtin.debug:
      msg: "{{Course}}{{USERNAME}}{{PASSWORD}}"  
