- name: useradd
  hosts: localhost
  become: yes 
  tasks:
  - name: id expense
    ansible.builtin.command: id expense2
    ignore_errors: true
    register: USER

  - name: hello
    ansible.builtin.debug:
      msg: "Hello"    
