- name: useradd
  hosts: localhost
  become: yes 
  tasks:
  - name: id expense
    ansible.builtin.command: id expense2
    ignore_errors: true
    register: USER

  - name: user info
    ansible.builtin.debug:
      msg: "{{USER}}"  

  - name: user add
    ansible.builtin.command: useradd expense
    when: USER.rc != 0    

    

  - name: hello
    ansible.builtin.debug:
      msg: "Hello"   


