- name: var check
  hosts: localhost
  become: no 
  vars:
    Course: "Devops"
    Tools:
    - AWS
    - Linux
    - yaml
    Exp:
      AWS: 2
      Linux: 3
      yaml: 5
    RealProj: true  
  tasks:
  - name: var check
    ansible.builtin.debug:
      msg: "{{Course}} {{Tools}} {{Exp}} {{RealProj}}"
