- name: cond check
  hosts: localhost
  become: no 
  tasks:
  - name: name check
    ansible.builtin.command: id expense4
    ignore_erros: true
    register: USER



  - name: Hello
    ansible.builtin.debug:
      msg: "Hello"  