- name: cond check
  hosts: localhost
  become: no 
  tasks:
  - name: cond check
    ansible.builtin.command: id expense4
    ignore_errors: true
    register: USER

  - name: user info
    ansible.builtin.debug:
      msg: "{{USER}}"  





  - name: Hello
    ansible.builtin.debug:
      msg: "Hello"  