- name: cond check
  hosts: localhost
  become: yes 
  tasks:
  - name: cond check
    ansible.builtin.command: id expense4
    ignore_errors: true
    register: USER

  - name: user info
    ansible.builtin.debug:
      msg: "{{USER}}" 

  - name: useradd expense4
    ansible.builtin.command: useradd expense4
    when: USER.rc != 0





  - name: Hello
    ansible.builtin.debug:
      msg: "Hello"  