- name: func check
  hosts: localhost
  become: no
  vars_prompt:
  - name: number
    prompt: "Enter the number:"
    private: no
  tasks:
  - name: number less than 10
    ansible.builtin.debug:
      msg: "{{number}} is less than 10"
    when: number | int < 10  

  - name: number greater than 10
    ansible.builtin.debug:
      msg: "{{number}} is greater than 10"
    when: number | int >= 10    

  - name: default value
    ansible.builtin.debug:
      msg: "{{HELLO | default('Ansible') }}"  

  - name: upper case
    vars:
     greetings: "Hello madam"
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"

  - name: upper case
    vars:
     greetings: "Hello madam"
    ansible.builtin.debug:
     msg: "{{greetings | lower}}"    


