- name: func check
  hosts: localhost
  become: no
  tasks:
  - name: default
    ansible.builtin.debug:
      msg: "{{HELLO|default('Ansible')}}"

- name: lower check
  hosts: localhost
  become: no
  vars:
    greetings: "Hello GM" 
  tasks:
  - name: lower case check
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"

- name: upper check
  hosts: localhost
  become: no
  vars:
    greetings: "Hello GM" 
  tasks:
  - name: lower case check
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"

- name: unique
  hosts: localhost
  become: no 
  vars:
  - numbers: [1,2,3,4,4,3,4,3,4]
  tasks:
  - name: unique check
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"  

- name: min/max
  hosts: localhost
  become: no
  vars:
  - numbers: [12,1,5,6,7,8,9]
  tasks:
  - name: min/max
    ansible.builtin.debug:
      msg: "min:{{numbers | min}}, max: {{numbers | max}}"     

- name: dict2items
  hosts: localhost
  become: no
  vars:
    Train:
      Course: "Devops"
      Trainer: "Siva"
      Duration: "120hrs"
  tasks:
  - name: dict2items
    ansible.builtin.debug:
      msg: "{{Train | dict2items}}"  

- name: items2dict
  hosts: localhost
  become: no 
  vars:
  -list1:
    - "key": "Course","value": "Devops"
    - "key": "Trainer","value": "Siva"
    - "key": "Duration","value": "120hrs"
  tasks:
  - name: items2dict
    ansible.builtin.debug:
      msg: "{{list1}}"