- name: func
  hosts: localhost
  become: no
  vars_prompt:
  - name: number 
    prompt: "Enter number:"
    private: no 
  
  tasks:
    - name: smaller
      ansible.buitin.debug:
        msg: "{{number}} is less than 10"
      when: number  < 10

- name: smaller
  hosts: localhost
  become: no 
  tasks:
  - name: bigger
    ansible.builtin.debug:
      msg: "{{number}} is greater than 10"     
    when: number >= 10  