- name: func
  hosts: localhost
  become: no
  vars_prompt:
  - name: number 
    prompt: "Enter number:"
    private: no
  tasks:
  - name: less than 10
    ansible.builtin.debug:
      msg: "{{number}} is less than 10"

  - name: greater than 10
    ansible.builtin.debug:
      msg: "{{number}} is greater than 10"    

