- name: func check
  hosts: localhost
  become: no
  tasks:
  - name: default
    ansible.builtin.debug:
      msg: "{{greetings| default('Ansible')}}"

- name: func check 2
  hosts: localhost
  become: no 
  vars:
    greetings: "Welcome GM"
  tasks:
  - name: lower
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"

- name: func check 3
  hosts: localhost
  become: no 
  vars:
    greetings: "Welcome GM"
  tasks:
  - name: upper
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"  

- name: min max
  hosts: localhost
  become: no 
  vars:
  - array: [1,1,2,2,3,4,5,6,7,8,8,9]
  tasks:
  - name: min/max
    ansible.builtin.debug:
      msg: "{{array | unique}}"          
