- name: func check
  hosts: localhost
  become: no
  tasks:
  - name: default
    ansible.builtin.debug:
      msg: "{{greetings| default('Ansible')}}"

- name: func check 2
  hosts: localhost
  become: no 
  vars:
    greetings: "Welcome GM"
  tasks:
  - name: lower
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"

- name: func check 3
  hosts: localhost
  become: no 
  vars:
    greetings: "Welcome GM"
  tasks:
  - name: upper
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"  

- name: remove dups
  hosts: localhost
  become: no 
  vars:
  - array: [1,1,2,2,3,4,5,6,7,8,8,9]
  tasks:
  - name: remove dups
    ansible.builtin.debug:
      msg: "{{array | unique}}"   

- name: min/max
  hosts: localhost
  become: no 
  vars:
  - array: [21,20,19,3,4,5,6]
  tasks:
  - name: min/max
    ansible.builtin.debug:
      msg: "min: {{array | min}}, max: {{array | max}}"  

- name: dict2items
  hosts: localhost
  become: no 
  vars:
    dict1:
      Course: "Devops"
      Trainer: "siva"
      Duration: "120hours"
  tasks:
  - name: dict2items
    ansible.builtin.debug:
      msg: "{{dict1|dict2items}}" 

- name: items2dict
  hosts: localhost
  become: no
  vars:
    list1:
    - {"key": "Course","value": "Devops"}
    - {"key": "Trainer","value": "siva"}
    - {"key": "Duration","value": "120hours"}      
