# - name: loop2
#   hosts: web
#   become: yes
#   tasks:
#   - name: loops
#     ansible.builtin.dnf:
#       name: "{{item}}"
#       state: latest
#     loop:
#     - mysql
#     - nginx
#     - postfix  

- name: loop3
  hosts: web
  become: yes 
  tasks:
  - name: loops
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loops:
      {name: "mysql",state: "latest"} 
      {name: "nginx",state: "absent"}
      {name: "postfix",state: "absent"} 
