# - name: loop1
#   hosts: web
#   become: no 
#   tasks:
#   - name: loops
#     ansible.builtin.debug:
#       msg: "{{item}}"
#     loop:
#     - AWS
#     - Linux
#     - Devops  

- name: Loop2
  hosts: web
  become: yes 
  tasks:
  - name: Loop2 test
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - mysql
    - nginx 
    - postfix  
    
    