- name: configure backend
  hosts: backend
  become: yes 
  tasks:
  - name: disable node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable node js  
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: dnf install nodejs -y
    ansible.builtin.dnf:
      name: "{item}" 
      state: latest
    loop:
    - nodejs 
    - mysql  

  - name: PyMySQL install
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography
      executable: pip3.9     

  - name: uesr add expense # Hetero enerious.Work for all distors. Idemopotent. 
    ansible.builtin.user:
      name: expense
  - name: create directory
    ansible.builtin.file:
      path: /app 
      state: directory

  - name: download file
    ansible.builtin.get_url:
     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
     dest: /tmp/backend.zip 

  - name: unzip backend
    ansible.builtin.unarchive:
     src: /tmp/backend.zip
     dest: /app
     remote_src: yes

  - name: run npm in app directory  
    ansible.builtin.command: npm install
    args:
      chdir: /app 

  - name: copy backend service
    ansible.builtin.copy:
     src: backend.service
     dest: /etc/systemd/system/backend.service





              






    
    